# Generated by Django 2.2.1 on 2019-06-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_auto_20190614_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
