# Generated by Django 2.2.1 on 2019-06-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_auto_20190614_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
