# Generated by Django 2.2.1 on 2019-06-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treaties', '0002_treaty_filedocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treaty',
            old_name='contractStageCode',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='treaty',
            old_name='contractCode',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='treaty',
            old_name='contractType',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='treaty',
            old_name='counteragentCode',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='treaty',
            old_name='sumMoney',
            new_name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='treaty',
            name='dateOfSigning',
        ),
        migrations.RemoveField(
            model_name='treaty',
            name='fileDocument',
        ),
        migrations.RemoveField(
            model_name='treaty',
            name='periodOfValidity',
        ),
        migrations.RemoveField(
            model_name='treaty',
            name='placeOfStorage',
        ),
        migrations.RemoveField(
            model_name='treaty',
            name='requisite',
        ),
        migrations.RemoveField(
            model_name='treaty',
            name='sumNDS',
        ),
        migrations.AddField(
            model_name='treaty',
            name='mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
