# Generated by Django 2.2.1 on 2019-06-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treaties', '0003_auto_20190614_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='treaty',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
